### ISSUE TITLE
Client Crash 1.12

### ISSUE THREAD

**Issue by sofifreak** [OreCruncher/DynamicSurroundings#128] opened 2017-07-07 18:44 UTC
1.12-3.4.5.7

1.12 - 14.21.1.2400

[crash-2017-07-07_20.39.04-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1131996/crash-2017-07-07_20.39.04-client.txt)

Crash immediately after login.

**Comment by OreCruncher** [comment] 2017-07-07 18:45
Dupe of [#126]

**Closed by OreCruncher** 2017-07-07 18:45 UTC
