### ISSUE TITLE
Crash when going into the "Music and Sounds" GUI

### ISSUE THREAD

**Issue by trpg1** [OreCruncher/DynamicSurroundings#493] opened 2019-09-07 23:17 UTC
*Mod Version:*
1.12.2-3.5.4.3

*Forge Version:*
14.23.5.2846

*Link to crash log (if applicable):*
https://paste.dimdev.org/ayagirujip.mccrash

*Description:*
The game crashed when going to Options -> Music and Sounds. Electroblob's Wizardry is also installed which also adds a sound type to the music and sounds section.

**Comment by dottiekh** [comment] 2019-09-22 03:55
can confirm im also getting this, along with the EXTREMELY unhelpful crashlog. when i removed quark (unfortunately i didnt notice it in your list) my crash log became much more informative. here is a link to mine: https://paste.dimdev.org/udorawuhav.mccrash

**Comment by OreCruncher** [comment] 2019-10-05 17:41
Dupe of #491.

**Closed by OreCruncher** 2019-10-05 17:41 UTC
