### ISSUE TITLE
Conflict with Biomes O' Plenty?

### ISSUE THREAD

**Issue by Domaaaa** [OreCruncher/DynamicSurroundings#226] opened 2018-02-03 12:41 UTC
Mod version: 3.4.8.5

Forge version: 14.23.1.2604

This is what happens when I step into a wasteland biome.

![n1](https://user-images.githubusercontent.com/36104076/35767188-34d011b6-08f0-11e8-9f6f-0f297daa8a64.png)

![n2](https://user-images.githubusercontent.com/36104076/35767189-3878135e-08f0-11e8-8b27-9ce3f704f7f0.png)

**Comment by OreCruncher** [comment] 2018-02-03 12:59
Dupe of #120.  Going to be fixed for v3.4.9.1

**Closed by OreCruncher** 2018-02-03 12:59 UTC

**Comment by Domaaaa** [comment] 2018-02-03 13:02
Cool. Hopefully v3.4.9.1 comes out soon!
