### ISSUE TITLE
Waterfall sounds from removing blocks from rivers and lakes from under the water.

### ISSUE THREAD

**Issue by KaneHart** [OreCruncher/DynamicSurroundings#443] opened 2019-01-23 23:13 UTC
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.2BETA
*Forge Version:*
2807

*Description:*
So what is happening is when your digging in Water the waterfall type sound effects play none stop. I guess Minecraft does not correctly fill in source blocks under source blocks. Either way makes it sound really bad and annoying especially since it's not even really flowing like a waterfalls and looks exactly like a normal river / lake. 

Sadly it gets so annoying and bad you just want to end up removing it.

**Comment by OreCruncher** [comment] 2019-01-24 17:51
I believe this is a dupe of [#437]

**Closed by OreCruncher** 2019-01-24 17:51 UTC
