### ISSUE TITLE
[1.16.5] Game crashes directly after world loading - Java 9?

### ISSUE THREAD

**Issue by Zothen1973** [OreCruncher/DynamicSurroundings#662] opened 2021-01-29 08:26 UTC
1.16.5
Forge 36.0.0.7
DynamicSurroundings-1.16.4-4.0.3.6.jar

It seems to me this mod isn't compatible with Java 8 Runtime anymore.

[crash-2021-01-29_09.14.23-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/5892576/crash-2021-01-29_09.14.23-client.txt)

![grafik](https://user-images.githubusercontent.com/77007295/106250249-ae1d7980-6213-11eb-9154-eea172106614.png)

**Comment by ghost** [comment] 2021-01-29 09:23
Same issue for me.

Btw this is actually a dupe of #659.

**Comment by OreCruncher** [comment] 2021-01-29 12:54
Yep - its a dupe.

**Closed as completed by OreCruncher** 2021-01-29 12:54 UTC
