### ISSUE TITLE
Error in log executing scripts 

### ISSUE THREAD

**Issue by NerdCraft** [OreCruncher/DynamicSurroundings#41] opened 2017-02-22 20:40 UTC
Mod Version: 3.2.8.1

Forge Version: 12.18.3.2234

http://pastebin.com/y9HGMjxR

**Comment by OreCruncher** [comment] 2017-02-22 22:09
Modpack/mods?

**Comment by NerdCraft** [comment] 2017-02-22 22:17
modlist: https://i.cubeupload.com/oX8B9j.png
 
Yes, I did.

**Comment by OreCruncher** [comment] 2017-02-22 22:32
OK.  Think I know the problem.  Fix will be in the next beta.  Until then you need to un-disable the the block effect if the issue is causing you a problem.

**Closed** 2017-02-22 22:41 UTC
