### ISSUE TITLE
Lighting Level

### ISSUE THREAD

**Issue by KennyBurch** [OreCruncher/DynamicSurroundings#106] opened 2017-06-09 03:12 UTC
*Mod Version:*
DynamicSurroundings-1.10.2-3.4.5.3
*Forge Version:*
forge-1.10.2-12.18.3.2297-universal
*Link to crash log (if applicable):*
N/A
*Description:*
Lighting level HUD seems to have broken with the last update. All i get are zeros.

**Comment by RedlorMC** [comment] 2017-06-09 04:17
+1
Mod Ver: DynamicSurroundings1.11.2-3.4.5.3
Forge Ver: 13.20.0.2315

![2017-06-09_00 07 13](https://user-images.githubusercontent.com/7233185/26960851-5d0e73b6-4ca8-11e7-82ae-3a2fd41315c6.png)

I've fired up a fresh client instance with only DynamicSurroundings installed (using default configs) to ensure this was not being caused by something else. Enabling Sky+Block light levels does result in some variances, but generally all blocks indicate 15.

![2017-06-09_00 16 24](https://user-images.githubusercontent.com/7233185/26960926-e9bc6e9e-4ca8-11e7-87d8-a05b58d815f3.png)

**Comment by OreCruncher** [comment] 2017-06-09 04:35
@KennyBurch What happens when you place a torch?  Generally a with only block light the value would be 0 unless there is a block nearby that gives off light, such as a torch.  Block + Sky factors in any light because of it being day time.  Block+Sky will change values dynamically when the sun rises and sets.

**Comment by OreCruncher** [comment] 2017-06-09 13:08
Found the bugger.   Will be in the next update - probably a couple days.  Only thing affected by the bug is the light level hud.

**Comment by OreCruncher** [comment] 2017-06-15 14:02
Pushed v3.4.5.4 version that has a fix.

**Closed by OreCruncher** 2017-06-15 14:02 UTC
Labels: bug, fixed
