### ISSUE TITLE
Crash On World Load

### ISSUE THREAD

**Issue by InsomniaKitten** [OreCruncher/DynamicSurroundings#24] opened 2017-01-10 23:08 UTC
**Mod version:** [3.2.1.0](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2366646)
**Forge version:** [1.10.2-12.18.3.2202](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2202/forge-1.10.2-12.18.3.2202-changelog.txt)

Client crashes to desktop when loading into a singleplayer world.

**Crash report:** [hastebin.com/vejocijuyo](https://hastebin.com/vejocijuyo.txt)

**Comment by MafooHamhead** [comment] 2017-01-11 00:34
I get the same error too.

**Comment by OreCruncher** [comment] 2017-01-11 03:08
@InsomniaKitten @MafooHamhead Have you tried Forge 2185?  It's what I build against and is the the recommended version.

**Comment by MafooHamhead** [comment] 2017-01-11 03:12
@OreCruncher I personally have not tested it yet. I'll test it soon and let you know if the problem persists. I would be on 2185, but one mod requires 2202.

It's weird because the previous version of your mod works perfectly fine on 2202... Then I updated to your newest one and boom the issue popped up. I'm able to load in for a nanosecond (I can see the UI for that little bit) then I crash. Could it be a bug with forestry? I see apiary and instantly think forestry, as those beehives emit noise.

I'll be sure to test on 2185 though later.

**Comment by OreCruncher** [comment] 2017-01-11 03:16
@MafooHamhead It could be some other mod dorking around with the BlockPosMutable class.  I derive from that class to do some things.  It's barking because my class is looking for a field that no longer exists.  I have a basic Forge 2202 using MultiMC and the latest version of Dynamic Surroundings and do not see a problem.

**Comment by MafooHamhead** [comment] 2017-01-11 03:35
@OreCruncher Okay I just did some testing on Forge 2202. Your newest version of DS is not compatible with Foamfix. (That mod that lowers RAM usage.) I was using the coremod version (Anarchy) which I know is not supported, but your previous version works perfectly fine with the same version of Foamfix. 

I doubt it's necessarily your fault, but: 

DS 3.2.1.0 **is not** compatible with Foamfix 0.5.0 Anarchy. 

DS 3.2.0.0 **is** compatible with Foamfix 0.5.0 Anarchy.

I'm not sure if the non-coremod version is compatible.

**Comment by OreCruncher** [comment] 2017-01-11 03:39
Took a quick look at FoamFix source and it does mess with BlockPos.  Not sure what I can do about it at the moment.

**Comment by MafooHamhead** [comment] 2017-01-11 03:42
I just made a post on Foamfix's GitHub as well. Hopefully something can be solved! 👍

**Comment by OreCruncher** [comment] 2017-01-13 13:22
@MafooHamhead @InsomniaKitten asie posted a v0.5.1 version with the fix.  I tested it in my dev sandbox and it appears to work.

**Comment by OreCruncher** [comment] 2017-01-19 13:39
@MafooHamhead @InsomniaKitten Have either of you confirmed that the problem is fixed with the latest versions of FoamFix?

**Comment by Sunconure11** [comment] 2017-01-23 09:33
I play with FoamFix installed and I have not seen a crash between this mod and FoamFix. You should still ask @InsomniaKitten anyways though.

**Comment by Wh4tsMyName** [comment] 2017-02-11 23:25
I'm having a similar issue, but I don't use FoamFix. After I installed four mods in a row (Uncrafting Table, DynamicSurroundings, Realistic Item Drops and Sound Filters), Forge crashes whenever loading any world. Uninstalling DS fixes it, but I want that mod.

**Comment by LemADEC** [comment] 2017-02-11 23:47
@Wh4tsMyName please post your crashlogs

**Comment by OreCruncher** [comment] 2017-02-12 01:00
@Wh4tsMyName Yes, going to need the logs.  I loaded up the 1.11.x versions with the latest Dynamic Surroundings (v3.2.8.0) and no crash.

**Comment by Wh4tsMyName** [comment] 2017-02-12 01:33
@LemADEC @OreCruncher There are no logs, thanks to the new Minecraft launcher.

**Comment by LemADEC** [comment] 2017-02-12 02:00
There's always logs

**Comment by Wh4tsMyName** [comment] 2017-02-12 03:19
[Logs.](http://pastebin.com/Gsc7xSGkl)

**Comment by OreCruncher** [comment] 2017-02-12 03:25
@Wh4tsMyName Link is dead?

**Comment by Wh4tsMyName** [comment] 2017-02-12 04:04
How can I paste it here?

**Comment by LemADEC** [comment] 2017-02-12 08:25
Try this https://gist.github.com/

**Comment by Wh4tsMyName** [comment] 2017-02-13 02:13
[Gist.](https://gist.github.com/Wh4tsMyName/10ab06611b15d12f7a8a1a7ecec0c845)

**Comment by OreCruncher** [comment] 2017-02-13 03:00
Ah.  That's a bug in the mod StepUp.  Fix is in the latest release of StepUp.

**Comment by Wh4tsMyName** [comment] 2017-02-13 03:31
You sure it's StepUp? I remove DynamicSurroundings and it works fine.

**Comment by OreCruncher** [comment] 2017-02-13 03:35
Yep.  It's a bug in StepUp.  If you go look at the CurseForge it mentions the fix.

**Comment by Wh4tsMyName** [comment] 2017-02-13 04:21
Wow, that...actually worked. Thanks!

**Comment by OreCruncher** [comment] 2017-03-15 16:59
Going to close this issues as addressed.  Later version of FoamFix have a fix.

**Closed by OreCruncher** 2017-03-15 16:59 UTC
Labels: mod compat
