### ISSUE TITLE
[1.11.2] ArrayIndexOutOfBoundsException Error

### ISSUE THREAD

**Issue by SjetCraft** [OreCruncher/DynamicSurroundings#117] opened 2017-06-22 21:48 UTC
*Mod Version:*
1.11.2-3.4.5.5

*Forge Version:*
13.20.0.2315

*Link to crash log (if applicable):*
[https://gist.github.com/SjetCraft/7323016cbac27c999607404a9b466b76](Gist)

*Description:*
Crashing to desktop while next to falling water in the rain. Logging back in will just crash to desktop until Water Splash effects are disabled in the config. (Disabled both Water Splash effects and FountainJetEffect just to be safe)
_Note:_ Using Optifine and FoamFix

**Comment by OreCruncher** [comment] 2017-06-22 21:49
Dupe of [#116]

**Closed by OreCruncher** 2017-06-22 21:49 UTC

**Comment by SjetCraft** [comment] 2017-06-22 21:50
I just saw, was going to notify that it was a dupe. Will this be fixed in the next update?

**Comment by OreCruncher** [comment] 2017-06-22 21:51
Yes.  Will be posting a new build a little bit later.

**Comment by SjetCraft** [comment] 2017-06-22 21:54
Thank you for your quick response and hard work!
Mods like yours make Minecraft a consistently enjoyable experience.
