### ISSUE TITLE
Waterfall sound sometimes glitches out.

### ISSUE THREAD

**Issue by Gabnificent** [OreCruncher/DynamicSurroundings#442] opened 2019-01-22 18:10 UTC
*Mod Version:* 1.12.2 ~ 3.4.10.6

*Forge Version:* 14.23.5.2807

*Link to crash log (if applicable):* N/A

*Description:*

Flowing/falling water occasionally... breaks? Seemingly playing far too many copies of the sound, overlapping each other, making it sound like an electric motor, or something. 
The sound persists, even if I reload the chunk. And... if I try to disconnect from my server (so far only encountered it in multiplayer)... the sound persists into the main menu... and... even carried on when I loaded up a single-player world. When the SP world was loaded, it anchored itself to a specific block, so when I walked away... it got quieter?! I think the only real way to get it to stop is to restart minecraft.

It only seems to happen when there's a lot of water, and when it's generated in a new chunk (Or maybe just in a recently loaded chunk). And I -think- it's when there's an overhanging block, that the water flows under? Basically it's whenever the water is messy, and chaotic. Lots of blocks interacting with each other.

**Comment by sa13103** [comment] 2019-01-24 08:10
i have been experiencing this same issue, though it seems that it only needs one flowing source block in an area for it to happen. restarting seems to be the only solution ive come across. im running a pretty heavily modded pack, could this be stemming from an overload of memory usage? ill start disabling the water settings one by one to see if any prevent it from occurring.

**Comment by OreCruncher** [comment] 2019-01-24 17:51
I believe this is a dupe of [#437]

**Closed by OreCruncher** 2019-01-24 17:51 UTC
