### ISSUE TITLE
1.12.2 Biome Bundle/OTG Sound Loop Crash

### ISSUE THREAD

**Issue by Arcaes** [OreCruncher/DynamicSurroundings#183] opened 2017-11-18 06:09 UTC
*Mod Version:*
1.12.2
*Forge Version:*
forge-1.12.2-14.23.0.2542

*Link to crash log (if applicable):*
[01:04:05] [main/WARN] [dsurround]: Biome [SavannaEdge] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[01:04:05] [main/WARN] [FML]: No types have been added to Biome minecraft:void, types have been assigned on a best-effort guess: [PLAINS]
[01:04:05] [main/INFO] [dsurround]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu)
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/INFO] [dsurround]: CLIENT: Executing script for mod [mcp]
[01:04:05] [main/WARN] [dsurround]: Unable to locate biome [SavannaEdge] (com.pg85.otg.forge.generator.OTGBiome) after reload
[01:04:05] [main/WARN] [dsurround]: Biome [SavannaEdge] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[01:04:05] [main/INFO] [dsurround]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu)
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/INFO] [dsurround]: CLIENT: Executing script for mod [mcp]
[01:04:05] [main/WARN] [dsurround]: Unable to locate biome [SavannaEdge] (com.pg85.otg.forge.generator.OTGBiome) after reload
[01:04:05] [main/WARN] [dsurround]: Biome [SavannaEdge] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[01:04:05] [main/INFO] [dsurround]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu)
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/INFO] [dsurround]: CLIENT: Executing script for mod [mcp]
[01:04:05] [main/WARN] [dsurround]: Unable to locate biome [SavannaEdge] (com.pg85.otg.forge.generator.OTGBiome) after reload
[01:04:05] [main/WARN] [dsurround]: Biome [SavannaEdge] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[01:04:05] [main/INFO] [dsurround]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu)
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/INFO] [dsurround]: CLIENT: Executing script for mod [mcp]
[01:04:05] [main/WARN] [dsurround]: Unable to locate biome [SavannaEdge] (com.pg85.otg.forge.generator.OTGBiome) after reload
[01:04:05] [main/INFO] [dsurround]: DimensionInfo{id=0, name=overworld, seaLevel=63, cloudHeight=128, skyHeight=256, haze=true, aurora=true, weather=true, fog=true}
[01:04:05] [main/WARN] [dsurround]: Biome [SavannaEdge] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[01:04:05] [main/INFO] [dsurround]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu)
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]
[01:04:05] [main/WARN] [dsurround]: Cannot find sound that should be registered [meta:missing_sound]

Then this repeats at an impressive rate infinitley.

*Description:*
Howdy, using latest version of OTG and BiomeBundle. This crash only occurs in loading certain biomes, otherwise mod works fine. BiomeBundle is not technically updated for 1.12.2, but I am unsure if this type of problem would be fixed by anything changed by an official update. Once chunk containing certain biome is loaded, this "crash" (it just slows MC down so its unusable) happens. I tried disabling biome sounds, and got a similar crash with different sound message. Is it possible to fix this or disable DSurroundings custom sounds altogether? Either of those would help plenty. Thanks.

**Comment by Alaberti** [comment] 2017-11-29 19:15
@PG85 Is this similar to https://github.com/OreCruncher/DynamicSurroundings/issues/85 do you think?

**Comment by Zhaltor** [comment] 2017-11-29 23:12
Am having the exact same issue, running the latest version of both mods. It's not crashing per se, but it is causing the game to freeze forcing me to close it forcefully.

**Comment by Luke616** [comment] 2017-11-30 23:08
@Zhaltor I believe that the "lag near oceans" issue is because of the way DS generates its water splash particles. Biome Bundle's oceans generate a lot of blocks of flowing water downwards, which is likely not intended behavior but it isn't really harmful. However, DS recognizes each flowing water block as a waterfall and generates a metric ton of splash particles all across the ocean. Try setting this option in the config and see if that helps the lag:
        B:"Enable Water Splash"=false

**Comment by Zhaltor** [comment] 2017-11-30 23:26
@Luke616 Thanks, though it does not help much considering the game becomes unplayable at random when exploring due to an unknown issue.

**Comment by Luke616** [comment] 2017-11-30 23:36
@Zhaltor lol yeh hopefully this issue gets addressed soon

**Comment by Draylynn** [comment] 2017-12-04 00:17
FYI: @Zhaltor OTG (/w Biome Bundle) producing tons of AIR blocks in water biomes and subsequently spamming the client with splashes is now fixed; https://github.com/PG85/OpenTerrainGenerator/issues/84

But the "[18:25:39] [main/WARN]: Unable to locate biome [Frozen Forest] (com.pg85.otg.forge.generator.OTGBiome) after reload" looping behaviour is still a problem.

**Comment by Lunchb0ne** [comment] 2017-12-09 14:56
Yep have the same problem this is reallllly annoying hopefully this gets fixed soon as I love both the mods :/

**Comment by OreCruncher** [comment] 2017-12-09 19:54
I plan to get back to this in a week or so when Xmas break comes.  Should have time to address then.

**Comment by PeeGee85Spil** [comment] 2017-12-11 12:34
@OreCruncher Same here, have been busy lately but I hope to have time around Xmas to look at some mod compatiblity issues :).

**Comment by Aceyfacey** [comment] 2018-01-05 20:14
Hi,
Thanks for your awesome mod orecruncher. I've had this issue as well, wanted to make my biomes look better but sudden lag until I uninstalled dynamic surroundings. Any eta on the next build that will include this fix? I see you said its been fixed 2 days ago.

**Comment by OreCruncher** [comment] 2018-01-05 20:16
Fixed means I committed it to GitHub.  I plan to publish a BETA containing the fix sometime on 1/6.

**Comment by OreCruncher** [comment] 2018-01-06 18:01
Post v3.4.8.1 with the compat changes.

**Closed by OreCruncher** 2018-01-06 18:01 UTC
Labels: fixed, mod compat
