### ISSUE TITLE
Using Pixelmon Reforged 6.2.3 and Dynamic Surroundings (any version), no Minecraft sounds work

### ISSUE THREAD

**Issue by Lovatic123** [OreCruncher/DynamicSurroundings#297] opened 2018-03-27 21:12 UTC
[crash-2018-03-27_22.58.49-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1853825/crash-2018-03-27_22.58.49-client.txt)
[crash-2018-03-27_22.59.50-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1853826/crash-2018-03-27_22.59.50-client.txt)
[crash-2018-03-27_23.01.13-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/1853827/crash-2018-03-27_23.01.13-client.txt)

*Reforged 6.2.3*

*1.12.2-14.23.2.26.35*

Minecraft has no sounds when these mods are installed together. No music, pokemon voices, block breaking/interaction sounds etc. Tested with 3 different versions of Dynamic Surroundings - 2 of them wouldnt even load the game, but gave a crash report when the game had almost finished loading.

**Comment by OreCruncher** [comment] 2018-03-27 21:14
This looks to be a dupe of #296.

**Comment by OreCruncher** [comment] 2018-03-28 19:23
Marking this as fixed/closed since I believe it to be a dupe of 296.  The fixes are in build v3.4.9.10

**Closed by OreCruncher** 2018-03-28 19:23 UTC
