### ISSUE TITLE
Game hangs with some biomes from Biome Bundle

### ISSUE THREAD

**Issue by slidedrum** [OreCruncher/DynamicSurroundings#191] opened 2017-12-14 19:25 UTC
*Mod Version:*
1.12.2-3.4.7.2
*Forge Version:*
1.12.2-14.23.1.2555

*Link to crash log (if applicable):*
Doesn't crash, but here is the applicable part of the log.

[13:31:03] [main/WARN]: Biome [Uplands] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[13:31:03] [main/WARN]: No types have been added to Biome minecraft:void, types have been assigned on a best-effort guess: [PLAINS]
[13:31:03] [main/INFO]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu/)
[13:31:03] [main/WARN]: Cannot find sound that should be registered [meta:missing_sound]
[13:31:03] [main/WARN]: Cannot find sound that should be registered [meta:missing_sound]
[13:31:03] [main/INFO]: CLIENT: Executing script for mod [mcp]
[13:31:03] [main/WARN]: Unable to locate biome [Uplands] (com.pg85.otg.forge.generator.OTGBiome) after reload
[13:31:03] [main/WARN]: Biome [Uplands] not detected during initialization - forcing reload (class com.pg85.otg.forge.generator.OTGBiome)
[13:31:03] [main/INFO]: Resource pack DEFAULT: Presence by Ha3 (http://presencefootsteps.ha3.eu/)
[13:31:03] [main/WARN]: Cannot find sound that should be registered [meta:missing_sound]
[13:31:03] [main/WARN]: Cannot find sound that should be registered [meta:missing_sound]
[13:31:03] [main/INFO]: CLIENT: Executing script for mod [mcp]

repeats forever
*Description:*

As far as I can tell the game is trying to play some sound that doesn't exist for the biome Uplands.  And keeps trying to refresh to find it, never being able to.    It probably happens with some other biomes as well, but I don't know what they are.

I don't know much about this mod, but I have tried disabling biome sounds, and disabling auto-restart sound system.  Neither has fixed my issue.

*Repro steps*
Install Biome Bundle (found here https://minecraft.curseforge.com/projects/biome-bundle)
Install Dynamic Surroundings
Start a single player world using Biome Bundle with the seed "SlideMC" OR open any world with cheats enabled and type the command "/otg tp uplands"
The game will hang forever: https://i.imgur.com/u44UXZM.png

**Comment by OreCruncher** [comment] 2017-12-24 19:24
The latest OTG stuff is incompatible with DS at the moment.  It's on my list of things to see if I can get it to work.

**Comment by OreCruncher** [comment] 2017-12-28 20:44
Marking as dupe of [#183].

**Closed by OreCruncher** 2017-12-28 20:44 UTC
Labels: duplicate, mod compat
