### ISSUE TITLE
Client Crash ticking entity

### ISSUE THREAD

**Issue by kreezxil** [OreCruncher/DynamicSurroundings#260] opened 2018-02-24 16:18 UTC
*Mod Version:*
1.12.2-3.4.9.4

*Forge Version:*
14.23.2.2619

*Link to crash log (if applicable):*
https://gist.github.com/1079f599576c4438ead5bb79e3fe4fed

*Description:*
ticking entity crash of client

**Comment by OreCruncher** [comment] 2018-02-24 16:19
Dupe of [#257].

**Closed by OreCruncher** 2018-02-24 16:19 UTC
