### ISSUE TITLE
nether dust storm continues when rain in overworld stops

### ISSUE THREAD

**Issue by Hypsellis** [OreCruncher/DynamicSurroundings#89] opened 2017-05-13 09:49 UTC
The nether dust continue even when overworld rain stopped or if the player try to desctivate it with the weather clear command. The only way to stop it to get out of the nether and come back, and sometimes it doesn't work, obliged to reload the world.

**Comment by OreCruncher** [comment] 2017-05-13 13:18
In vanilla the dimensions have their own sets of timers for rain duration and what not.  I will have to take a look to see if things are working as intended.  Question: when you ran the /weather clear command were you in the nether or overworld?  If not in the nether have you tried running it in the nether? (Again, the weather system in the alternate dimensions are kinda separate based on my recollection.)

**Comment by OreCruncher** [comment] 2017-05-13 13:36
Just looked at the code.  Something changed in the underlying Forge/Vanilla implementation.  Oh joy!  This one is going to be fun.

**Comment by OreCruncher** [comment] 2017-05-13 14:33
Sorry my bad.  My world was a bit corrupt from all the gyrations.  The rain duration timers are separate for each dimension so the situation you outline above is possible.

**Comment by OreCruncher** [comment] 2017-05-13 16:31
I did find  a bug related to nether and when the effects actually show in the client.  This fix will be in the next BETA.  It could be the cause of what you are describing.

**Comment by OreCruncher** [comment] 2017-05-16 16:41
Pushed a v3.4.3.0 version with this fix.

**Closed by OreCruncher** 2017-05-16 16:41 UTC
Labels: bug, fixed
