### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [OreCruncher/DynamicSurroundings#234] opened 2018-02-07 15:37 UTC
MC/F 1.12.2/2613

Just clobbered a small green slime, game froze. Checked report, think it's yours - apologies if not.

https://pastebin.com/J2PasU6a

**Comment by OreCruncher** [comment] 2018-02-07 15:39
Yep, its mine.  Dupe of [#232].  Thanks for letting me know!

**Closed by OreCruncher** 2018-02-07 15:39 UTC
