### ISSUE TITLE
[BUG] Shaders interfering with Auroras

### ISSUE THREAD

**Issue by Rapolis** [OreCruncher/DynamicSurroundings#102] opened 2017-06-01 08:31 UTC
*Mod Version: 1.11.2-3.4.5.1*

*Forge Version: 1.11.2-13.20.0.2228*

*Link to crash log (if applicable): NONE*

*Description: This happens a lot in coldest of areas. I tried with every shader I could try and use and it just causes random errors to the Aurora. (Flickering, almost invisible, making your screen turn black, weird coloring.)
I hope you can fix the Aurora rendering code to not interfere with shaders. That's how much I can explain.*

*Screenshots*
http://prntscr.com/fekeh4
That's how much I can get on one shaderpack. No other causes this error. It appears almost invisible and flickers.

**Comment by OreCruncher** [comment] 2017-06-01 12:17
Duplicate of [#68].  Not much I can do.  Shaders want to own the sky.  You can turn off Auroras in Dynamic Surroundings.  Note that this is a common compatibility issue between mods and shader packs.

**Closed by OreCruncher** 2017-06-01 12:17 UTC
