### ISSUE TITLE
Disappear settings Just Enough Buttons

### ISSUE THREAD

**Issue by kellixon** [OreCruncher/DynamicSurroundings#379] opened 2018-09-19 10:15 UTC
DynamicSurroundings 3.4.9.16
Forge 1.12.2-14.23.4.2760
Disappear JEI settings, after installation DynamicSurroundings (border and level lighting)
![2018-09-19_12 32 08](https://user-images.githubusercontent.com/22012731/45747298-130d4180-bc0e-11e8-907d-8f795464f06f.png)
![2018-09-19_12 32 33](https://user-images.githubusercontent.com/22012731/45747300-156f9b80-bc0e-11e8-8bd7-e195760fb837.png)

**Comment by kellixon** [comment] 2018-09-29 05:31
JEI 4.12.1.215, JEI 4.12.1.217.

**Comment by OreCruncher** [comment] 2018-09-29 15:43
Ah - you are referring to Just Enough Buttons, not Just Enough Items.  JEB is working as intended.  The mod does not display the keybinds for light level overlay and chunk boundaries if Dynamic Surroundings is installed.  Refer to [this line of code](https://github.com/univrsal/JustEnoughButtons/blob/master/src/main/java/de/universallp/justenoughbuttons/client/ClientProxy.java#L130).

**Comment by OreCruncher** [comment] 2018-11-05 18:10
@kellixon Following up.  Were you able to confirm it was Just Enough Buttons?

**Comment by kellixon** [comment] 2018-11-05 18:40
Yes

**Comment by OreCruncher** [comment] 2018-11-05 21:33
Good.  I will go ahead and close this issue out then.  If you have any other issues let me know.

**Closed by OreCruncher** 2018-11-05 21:33 UTC
Labels: not my bug
