### ISSUE TITLE
Crash when removing streams mod after generating it.

### ISSUE THREAD

**Issue by darkshadow1809** [OreCruncher/DynamicSurroundings#467] opened 2019-04-29 04:08 UTC
*Mod Version:*
1.12.2.3.5.4.3
*Forge Version:*
14.23.5.2836

*Link to crash log (if applicable):*
https://paste.dimdev.org/sakogekehu.mccrash
*Description:*
Happens whenever you remove Streams after the river has generated, (had to because of incompatibility with worldgen on existing world)

**Comment by OreCruncher** [comment] 2019-10-05 23:12
Dupe of #469.  Though this one was first (thanks!) the other was tagged, etc.

**Closed by OreCruncher** 2019-10-05 23:12 UTC
