### ISSUE TITLE
Dsurroundgins Crash

### ISSUE THREAD

**Issue by Zergmazter** [OreCruncher/DynamicSurroundings#435] opened 2019-01-05 07:33 UTC
*Mod Version: Dsurroundgins ending in 3.5.4 1Beta*

*Forge Version: Forge-14.23.5.2796 *

*Link to crash log (if applicable):*
https://paste.dimdev.org/namozaduna.mccrash

*Description:*

I was flying in creative and it crashed.

**Comment by OreCruncher** [comment] 2019-01-05 12:04
Can you link the client log for the session where the crash happened?

**Comment by OreCruncher** [comment] 2019-01-05 12:42
Best I can determine is that there is a new IBlockState that wasn't present during the load complete event - which is darn right weird.  I sure hope that Forge for 1.13 tightens up registrations. :\  I am putting in work around code to handle this issue on the fly.  I will still like to have the client log to see if there was anything else strange going on.

**Comment by OreCruncher** [comment] 2019-01-05 15:13
Yep - looks the same.

**Comment by OreCruncher** [comment] 2019-01-05 15:15
I am fairly sure this is a dupe of #434 so I am going to close this one in favor of the other.

**Closed by OreCruncher** 2019-01-05 15:15 UTC
Labels: bug, duplicate
